//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanjiScreenSaver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KanjiScreenSaver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;kanjiinfo&gt;
        ///	&lt;kanji char=&quot;百&quot; meaning=&quot;Hundred&quot;&gt;
        ///		&lt;keyword word=&quot;百&quot; kana=&quot;ひゃく&quot; romaji=&quot;hyaku&quot; meaning=&quot;hundred&quot; /&gt;
        ///		&lt;keyword word=&quot;百科事典&quot; kana=&quot;ひゃっかじてん&quot; romaji=&quot;hyakkajiten&quot; meaning=&quot;encyclopedia&quot; /&gt;
        ///	&lt;/kanji&gt;
        ///	&lt;kanji char=&quot;一&quot; meaning=&quot;One&quot;&gt;
        ///		&lt;keyword word=&quot;一&quot; kana=&quot;いち&quot; romaji=&quot;ichi&quot; meaning=&quot;one&quot; /&gt;
        ///		&lt;keyword word=&quot;統一化&quot; kana=&quot;とういつか&quot; romaji=&quot;touitsuka&quot; meaning=&quot;unify&quot; /&gt;
        ///	&lt;/kanji&gt;
        ///	&lt;kanji char=&quot;本&quot; meaning=&quot;Book&quot;&gt;
        ///		&lt;keyword word=&quot;本&quot; kana=&quot;ほん&quot; romaji=&quot;hon&quot; meaning=&quot;book&quot; /&gt;
        ///		&lt;keyword word=&quot;本当&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Kanji {
            get {
                return ResourceManager.GetString("Kanji", resourceCulture);
            }
        }
    }
}
